/**
 * @externs
 * @suppress {duplicate,checkTypes,undefinedNames}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/export_as_namespace_importeq/export_as_namespace_importeq.d.ts:
/** @const */
var test_files$export_as_namespace_importeq$export_as_namespace_importeq = {};
/** @const */
test_files$export_as_namespace_importeq$export_as_namespace_importeq.anamespace = {};
/**
 * @constructor
 * @struct
 */
test_files$export_as_namespace_importeq$export_as_namespace_importeq.anamespace.NamespacedClass = function() {};

/**
 * @return {string}
 */
test_files$export_as_namespace_importeq$export_as_namespace_importeq.anamespace.NamespacedClass.prototype.method = function() {};

// Publish non-shimmed external module externs as a Closure namespace.
goog.provide('test_files.export_as_namespace_importeq.export_as_namespace_importeq');
/** @const */
test_files.export_as_namespace_importeq.export_as_namespace_importeq = test_files$export_as_namespace_importeq$export_as_namespace_importeq.anamespace;
// export as namespace exportedNamespaceIncludingImportEq
/** @const */
var exportedNamespaceIncludingImportEq = test_files$export_as_namespace_importeq$export_as_namespace_importeq.anamespace;
